### ISSUE TITLE
expand() does not accept 1-1 navigation properties

### ISSUE THREAD

**Issue by buchatsky** [cbrianball/ts-odata-client#10]
Currently expand() accept only 1-M relationships which are represented by arrays. Trying to expand an object entity brings a syntax error.
Assuming Product-Supplier 1-1 relationship (from Northwind test database):
```
/* product.ts */
export class Product  {
  productId: number;
  categoryId: number;
  discontinued: boolean;
  productName: string;
  quantityPerUnit: string;
  reorderLevel: number;
  supplierId: number;
  unitPrice: number;
  unitsInStock: number;
  unitsOnOrder: number;
  category: Category;
  //orderDetails: OrderDetail[];
  supplier: Supplier;
}

/* northwind-context.ts * /
export class NorthwindContext extends ODataV4Context {
  constructor() {
    super('api/');
  }
  get products() { return this.createQuery<Product>('products'); }
}

/* products.component.ts */
  async getAllProducts() {
    const result = await this.context.products
      .filter(e => e.productName.$startsWith('C'))
      .expand('supplier')  // TS error here
      .getManyAsync();
  
    this.products = result.value;
  }

```
brings an error: "TS2345  (TS) Argument of type 'string' is not assignable to parameter of type 'never'."
Workaround: patching ODataQuery.d.ts:

```
//expand<K extends keyof SubType<T, any[]>>(...fields: K[]): ODataQuery<T, U & Pick<T, K>>;
expand<K extends keyof SubType<T, object>>(...fields: K[]): ODataQuery<T, U & Pick<T, K>>;
```
'object' implies both arrays and objects proper.

ts-odata-client  "version": "2.0.0"

**Comment by cbrianball** [comment]
I've updated the code, in a branch, to allow expand on any field that isn't a string, number, boolean, or date. Do you think this will work for you?
https://github.com/cbrianball/ts-odata-client/commit/dcd815e4d8e68351dcd4ba52ed4df0bcfab89700#diff-063e6af13d9b5b09f3b2cd288799f485b1e707d5fc7443d8bad5f6e4b167967cR109
