### ISSUE TITLE
How can I disable excluding array properties in query result?

### ISSUE THREAD

**Issue by buchatsky** [cbrianball/ts-odata-client#11]
I want to use the same entity class for queries with or without expanding its 1-M navigation properties represented as arrays:
```
export class Product  {
  productId: number;
  categoryId: number;
  discontinued: boolean;
  productName: string;
  quantityPerUnit: string;
  reorderLevel: number;
  supplierId: number;
  unitPrice: number;
  unitsInStock: number;
  unitsOnOrder: number;
  category: Category;
  orderDetails: OrderDetail[];  // property in question
  supplier: Supplier;
}
```
If I don't expand 'orderDetails':
```
    const result = await this.context.products
      .getManyAsync();
      //.expand('orderDetails')

    this.products = result.value; // error here

```
TS brings me an error: "TS2322  (TS) Type 'ReplaceDateWithString<ExcludeProperties<Product, any[]>>[]' is not assignable to type 'Product[]'.
  Property 'orderDetails' is missing in type 'ReplaceDateWithString<ExcludeProperties<Product, any[]>>' but required in type 'Product'."
Workaround: making all entity type navigation properties optional (ar even all but ID in case os select)
```
export class Product  {
...
  orderDetails?: OrderDetail[];
...
}
```

**Comment by cbrianball** [comment]
I'll look into this. Most of my implementation is based on the OData service I work with professionally. For that service, none of the collection-based navigation properties are expanded by default (you have to explicitly expand them). Is that not your experience?

**Comment by buchatsky** [comment]
I would prefer having that properties unassigned than missing, and having the exact entity type like Breeze does.
I usually have code like this:

```
export class Product {
  productId: number;
  ...
  orderDetails: OrderDetail[];
  supplier: Supplier;
}
... 
let products: Product[];
...
  const result = await this.context.products
    .filter(e => e.productName.$startsWith('C'))
    .getManyAsync();
products = result.value;

```

**Comment by buchatsky** [comment]
And I also got errors that are caused by replacing member's Date type  with string type, and type casting like 
`this.orders = <Order[]>result.value;`
does not help, I get errors like
Type 'ReplaceDateWithString<ExcludeProperties<Order, any[]>>' is not comparable to type 'Order'.
Types of property 'orderDate' are incompatible.
Type 'string' is not comparable to type 'Date'

**Comment by cbrianball** [comment]
> And I also got errors that are caused by replacing member's Date type with string type, and type casting like `this.orders = <Order[]>result.value;` does not help, I get errors like Type 'ReplaceDateWithString<ExcludeProperties<Order, any[]>>' is not comparable to type 'Order'. Types of property 'orderDate' are incompatible. Type 'string' is not comparable to type 'Date'

That makes sense. OData returns dates as strings (since JSON doesn't have a native way to represent dates). You would need to process the results in some way to convert it back into the type you want.

In v1 of this library I did not convert the dates to strings in the types, which caused issues as TypeScript thought a property was a date (so you could call methods of the Date type), but at runtime, it was really a string, so you would get a runtime error.

**Comment by cbrianball** [comment]
> I would prefer having that properties unassigned than missing, and having the exact entity type returned like Breeze does. I usually have code like this:
> 
> ```
> export class Product {
>   productId: number;
>   ...
>   orderDetails: OrderDetail[];
>   supplier: Supplier;
> }
> ... 
> let products: Product[];
> ...
>   const result = await this.context.products
>     .filter(e => e.productName.$startsWith('C'))
>     .getManyAsync();
> products = result.value;
> ```

Looks like the issue is here:
https://github.com/cbrianball/ts-odata-client/blob/561ac8cf7b67e8de43f0c33f82f45455c546c1c0/src/lib/ODataV4Context.ts#L14-L16

ODataV4QueryProvider can do what you want it to do, but the context (that I assume you are inheriting from) is making the assumption. Can you write your own context (just copy paste the one above and make the change you want) and let me know if that solves the problem?

If so, I'll make an update to where the createQuery method in the context will allow you to specify the second type passed into the query provider.

**Comment by buchatsky** [comment]
I did not manage to fix that in my custom ODataV4Context because ODataQuery<> class requires ExcludeProperties<T, any[]> in its definition. But I fixed the problem with making all array properties optional:
```
export class Product {
  ...
  orderDetails?: OrderDetail[];
 }
```
And to be consecutive, not only array props (1-M) but also all object props (1-1) should be excluded if they are not expanded, shouldn' they?

**Comment by cbrianball** [comment]
Please check out this commit https://github.com/cbrianball/ts-odata-client/commit/de9276e65eb16cc43b80515cb420c4cd41953e05

createQuery method assumes the excluded properties by default, but you can now define was the default shape of the result looks like:

    this.createQuery<User, User>("/users");

If you omit the second type, it defaults to the existing behavior (of excluding arrays):

    this.createQuery<User>("/users");

**Comment by buchatsky** [comment]
Yes, it solved the problem without modifying TS entity types, thank you

**Comment by cbrianball** [comment]
Thanks. I've pushed version 2.0.1 to NPM. It should be available soon. This includes fixes for this issue as well as the other issue you submitted.
