### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by srizzling** [cbrianball/ts-odata-client#15]
Our Odata API is protected using OAuth - I really like the use of this library - how may I make an authenticated responses?

**Comment by cbrianball** [comment]
Hi, thanks for your interest!

Here's a test that demonstrates how you can accomplish this:
https://github.com/cbrianball/ts-odata-client/blob/af3f02804f36ad2dd9235dd097085f149a367186/test/requestInit.test.ts#L41-L46

It may not be straight forward, but when using an ODataContextV4 (or if you use ODataV4QueryProvider directly), there's a second argument that is an options object of type ODataV4Options:
https://github.com/cbrianball/ts-odata-client/blob/af3f02804f36ad2dd9235dd097085f149a367186/src/lib/ODataV4QueryProvider.ts#L7-L9

The only currently supported field is `requestInit`, which is a function that will return a [`RequestInit`](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request#init) type, or a Promise that will resolve to a `RequestInit` type.

The above link will take you to the documentation about what the `RequestInit` object is. In my experience with OAuth, you will likely need to add a token to the `Authorization` header and the value will be in the format of `Bearer X` where X is replaced with then token value you've retrieved from your OAuth provider.

Let me know if this doesn't make sense or isn't working as expected.
